name: 'Push Docker GCR'
description: 'Push docker image to Google Container Registry'
inputs:
  gcr_host:
    description: 'Google Container Registry Host'
    default: 'gcr.io'
  image_name:
    description: 'Docker Image Name'
    required: true
  image_tag:
    description: 'Docker Image Tag'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
    GOOGLE_COMPUTE_ZONE: ${{ secrets.GOOGLE_COMPUTE_ZONE }}
    GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
